### ISSUE TITLE
Test failure doesn't change exit code

### ISSUE THREAD

**Issue by KellerFuchs** [hashbang/userdb#10]
`psql` returns with a 0 exit code even when tests fail.

This is problematic, since it makes the CI completely useless.

**Comment by KellerFuchs** [comment]
That's funny: it seems to only occur on Postgre 9.5 (Debian testing).
On Travis, it fails as expected.

**Comment by KellerFuchs** [comment]
Nevermind, it failed on Travis because it stalled.

**Comment by daurnimator** [comment]
`psql -c` returns non-zero exit codes just fine:

```
$ psql 
psql (9.5.3)
Type "help" for help.

daurnimator=# create function foo() returns void
daurnimator-# language plpgsql as $$
daurnimator$# begin
daurnimator$# raise invalid_password using message = 'test';
daurnimator$# end $$;
CREATE FUNCTION
daurnimator=# select foo();
ERROR:  test
daurnimator=# \q
$ psql -c 'select foo();'
ERROR:  test
exit=1 $ psql <<< 'select foo();'
ERROR:  test
$
```

**Comment by KellerFuchs** [comment]
@daurnimator Yes.
What I meant is that the error is caught by `plpgunit` before hitting the toplevel, so `psql` doesn't perceive the execution as erroneous.

The end result is still that `psql`, in our test suite, returns 0 regardless of whether tests pass (through no fault of its own).
