### ISSUE TITLE
Impose size limits on user data

### ISSUE THREAD

**Issue by KellerFuchs** [hashbang/userdb#11]
Currently, nothing in the schema prevents users from storing multi-megabytes (or more) JSON blobs...

We should figure out how to enforce a size constraint.

**Comment by KellerFuchs** [comment]
@daurnimator Assigned you as you are the resident PgSQL expert (and some quick Googling didn't yield anything)

**Comment by daurnimator** [comment]
As `jsonb` is based on text, to get the size you cast to text and use the `length` function.
To add this to the schema use a `CHECK` in the column definition
