### ISSUE TITLE
Improve the `max_users` constraint

### ISSUE THREAD

**Issue by KellerFuchs** [hashbang/userdb#17]
We have a `max_users` constraint to enforce server-specific max number of users, which needs several improvements:
- [ ] unit tests for the constraint;
- [ ] perform the check when the `hosts` table is updated, as the `maxusers` setting might have been reduced;
- [ ] reuse data from the `hosts_statistics` view, rather than duplicating code.

**Comment by RyanSquared** [comment]
Would # 2 be as simple as:

```sql
create function check_hosts_for_user() returns trigger
    language plpgsql as $$
    begin
        raise foreign_key_violation using message = 'maxUsers too high for host: '||new.host;
    end $$;
create constraint trigger max_users_on_host
    after update on hosts
    for each row
    when (old.maxusers <> new.maxusers and (select count(*) from passwd where passwd.host = new.name) >= new.maxusers)
    execute procedure check_hosts_for_user();
```

I don't think it's as simple as just using `max_users` on top of hosts; it might clutter the file a bit more but I think this one should perform fine without some hack to get `old` and `new` working with multiple, different tables.

**Comment by daurnimator** [comment]
Need to check on insert as well as update.

**Comment by RyanSquared** [comment]
No you don't; when you insert a new host, there's no users linked.

**Comment by RyanSquared** [comment]
I don't think # 3 is necessary as it would create a JOIN on every host where we don't actually need it. I feel like they're two separate components and trying to mix them together will create more spaghetti than we're trying to avoid copying.

**Comment by daurnimator** [comment]
> >= old.maxusers

Shouldn't that be `new.maxusers`?

**Comment by RyanSquared** [comment]
Yep, thanks.

**Comment by RyanSquared** [comment]
Fixed up code, will PR in a bit
