### ISSUE TITLE
Json vs additional meta table?

### ISSUE THREAD

**Issue by mayli** [hashbang/userdb#21]
> In the passwd and hosts tables, a data (binary) JSON object holds some non-relational data. 

What about let's use another additional table for these additional data?
eg.  for table `passwd` we could have a table `passwd_ext` with the following schema

| user (foreign key from passwd.uid)        | key           | value  |
| ------------- |:-------------:| -----:|
| 10000      | ssh_keys | xxxxxxxx |
| 10000      | name      |   Gaben |
| 10000      | shell      |   /bin/bash |

The `*_ext` tables can have a fixed schema and functions to enforce constrains. And also able to be updated to hold additional information without changing the schema.

The benefits is this will get rid of requirements of/dependencies on json and limitation is there will be no structure for the values column, they must be in plaintext (which might be a benefit in some cases).

**Comment by KellerFuchs** [comment]
What would be the benefit of using an extra table this way?
Also, what would be the type for the value `column`?  (`any` [isn't a valid column type](https://www.postgresql.org/docs/current/static/datatype-pseudo.html))

There are several benefits to using `jsonb` there, (some of?) which are documented in `DESIGN.md`:
1. Applications that use the DB can return the JSON object, augmented with whichever data they computed/queried.
   That makes it easy to automatically expose additional information about hosts or users.
2. We can enforce JSON schemas on the auxiliary data, which are shared between the DB, API definition, and applications.
3. `jsonb` is a reasonably-efficient representation of the auxiliary data.
4. We can easily bound the size of the `jsonb` object with a simple `CHECK` constraint.

**Comment by mayli** [comment]
There are two extreme of database schema: schema vs schema less. The traditional sql database has a fixed schema, and which requires `alter table` when new fields are added. The schema less doesn't have any requirement on schema, which usually stores everything as json. This design seems mixing both approach when introduce the `data` field.

In the STYLEGUIDE.md:
>Try to use only standard SQL functions instead of vendor specific functions for reasons of portability.

I really feel that json thing is not part of standard SQL functions.

In the design doc:
> non-relational data: SSH keys, full name, preferred shell, ...

By embedding all extra attributes into the bjson, it might hard to express the relation in traditional sql.
for mandatory, common and non repeatable fields such at `name` and `shell`, i think we can just put these fields as columns it in the `passwd` table. For repeatable fields such as `ssh_keys`, we can put it into the `passwd_ext` table, and query on keys can be done by a simple join.

> the data object can be easily extended with additional information without having to modify the schema (or even coordinate with the administrators);

Since there **is** a json schema for the `data` field, if it was enforced, the above statement doesn't hold true.

> Some fields, like shell or ssh_keys, are used by #! infrastructure; validating the JSON objects prevents users from accidentally losing access to their own account in this way.

the `shell` field can be easily validated if it's a column in the `passwd` table.

Permissions
> ssh: needs read access to the passwd.{name,data} columns.

With the `passwd_ext` table, ssh doesn't really needs to access the entire `data` field, it only needs to access (uid=$uid, key="ssh_key") in the `passwd_ext` table.

In general, I don't think the data.json provides any benefit in userdb.

**Comment by KellerFuchs** [comment]
I'm replying to all your points here, but please reply to my previous comment at some point.
Otherwise, it would be hard to have much of a conversation going on  :V

> >    the data object can be easily extended with additional information without having to modify the schema (or even coordinate with the administrators);
>
> Since there is a json schema for the data field, if it was enforced, the above statement doesn't hold true.

There is a JSON schema, it is enforced, and the statement still holds.  JSON schemas can be written in a forward-compatible way; in our case, we simply enforce constraints about properties (in the JSON sense) that the schema knows about, without forbidding the presence of additional properties.

> >    non-relational data: SSH keys, full name, preferred shell, ...
>
> By embedding all extra attributes into the bjson, it might hard to express the relation in traditional sql.

Which relation?  What you quote specifically says that non-relational data (i.e. data not involved in relations with any other table beyond “being attached to a row”) is the target usecase for this.

> > Some fields, like shell or ssh_keys, are used by #! infrastructure; validating the JSON objects prevents users from accidentally losing access to their own account in this way.
>
> the shell field can be easily validated if it's a column in the passwd table.

You are quoting a paragraph explaining why validating the `data` object is useful; it's not stating that it cannot be done if the data was in a column.

> >    ssh: needs read access to the passwd.{name,data} columns.
>
> With the passwd_ext table, ssh doesn't really needs to access the entire data field, it only needs to access (uid=$uid, key="ssh_key") in the passwd_ext table.

1. Granting access to only a specific property of `data` is perfectly possible.
2. The entire world has read-only access to the database. (Literally, in the case of the planned “federation” mechanism.)

**Comment by KellerFuchs** [comment]
PS: You have yet to provide a benefit for the `_ext` table way, beyond “having no JSON”.
(Note that `jsonb` is not actual JSON: Postgres internally uses a binary representation; it does, however, represent the same domain as JSON values and can be converted to/from it.)

**Comment by mayli** [comment]
the benefit is
 - the *_ext table are simple key, value pairs
 - extendable without changing schema
 - easy parse-able in shell or there places without json
 - portable, pure sql
 - not necessary if all necessary fields are present in the main table
 - avoid plurals ssh_keys -> ssh_key

**Comment by daurnimator** [comment]
> the *_ext table are simple key, value pairs

This makes querying the table quite complex.

> portable, pure sql

This is not a goal for us.
I have no problem relying on postgres specific capabilities; infact, I encourage the addition of PLPGSQL triggers to keep separation of schemas and maintain constraints.

> not necessary if all necessary fields are present in the main table

I don't see what this buys us?

---------
> STYLEGUIDE.md

I disagree with the majority of the style guide. I missed when it got added as part of a PR :( I've been meaning to come back and remove/replace it; but I haven't had time.

----------

The point of the json column was to have a way for programs to add fields without bothering with a schema change. I was originally advocating for adding columns manually to the main table as we needed them, but I was persuaded that an extra column for prototyping things before adding a column for them would be good for the community.

**Comment by mayli** [comment]
Ok, but since the `data` field is for additional data that comes after the initial design, do we want to put as much data as we can to columns? Are we going to utilize the `data` field as much as possible or avoid it when possible?

If it's the former case, we can actually embed all other columns to the `data` field, and use posgresql as a k/v database.
In the latter case, we should put well known fields `GECOS`, `shell` and etc to their own columns.

I didn't see where is the line to decide which fields goes to `data`.

**Comment by KellerFuchs** [comment]
The “line to decide which fields go to `data`” is documented in `DESIGN.md`: non-relational data (i.e. data with no constraints that involves other rows or other tables).

`homedir` is an odd one out, since it violates both “non-relational data is in `data`” and “no data is duplicated (to avoid inconsistencies)” (the homedir in our deployment is guaranteed to be `/home/${passwd.name}`).  I will make a PR to deal with it, thanks for making me notice it.  :)

**Comment by KellerFuchs** [comment]
PS: If we ever go for a more complex homedir scheme, generating and adding the new data will be pretty easy.

**Comment by mayli** [comment]
ok, thanks for the explanation. i will close this issue for now.
