### ISSUE TITLE
Compatiblilty with conf/dbschema.sql?

### ISSUE THREAD

**Issue by mayli** [hashbang/userdb#22]
In designing our own schema, are we going to keep our schema compatible with [the schema in libnss-pgsql](https://github.com/jandd/libnss-pgsql/blob/master/conf/dbschema.sql)?

**Comment by KellerFuchs** [comment]
I checked back then, and the documented schema isn't an actual requirement (and I should file a documentation bug).  `libnss-pgsql` directly runs whichever queries you provide.

**Comment by mayli** [comment]
Yes, those queries are customizable, but do we want to customize it when debian distros ship a working one?

**Comment by KellerFuchs** [comment]
Yes, definitely:
- the provided schema doesn't accomodate for a number of things we need/want (additional data, binding users to hosts, ...);
- there are a number of things that the provided schema does that we avoid for good reason (typically, making an actual bug we encountered in [provisor](https://github.com/hashbang/provisor) structurally impossible).

If there are specific design decisions you find problematic, feel free to check `DESIGN.md` and open an issue if necessary.

**Comment by KellerFuchs** [comment]
PS: Feel free to reopen the issue if you feel there are still concerns there.
