### ISSUE TITLE
Usernames to disallow

### ISSUE THREAD

**Issue by daurnimator** [hashbang/userdb#27]
https://ldpreload.com/blog/names-to-reserve has a good summary

**Comment by RyanSquared** [comment]
What would be a good way to go about blocking names in a database? I was thinking just add in records for every name so it gets denied on insertion due to being unique, but there's probably a better way.

**Comment by daurnimator** [comment]
> What would be a good way to go about blocking names in a database? I was thinking just add in records for every name so it gets denied on insertion due to being unique, but there's probably a better way.

We could either add some static rows and rely on a uniqueness constraint. Or we could add a function `is_reserved_username` that keeps a dataset elsewhere.

I'm leaning towards the latter solution.

**Comment by RyanSquared** [comment]
```sql
-- prevent users from taking names typically reserved for sysadmins
CREATE TABLE "banned_usernames" (
    "name" username_t UNIQUE NOT NULL
);
create function check_banned_username() returns trigger
    language plpgsql as $$
    begin
        if (exists(select 1 from banned_usernames where name = new.name)) then
            raise check_violation using message = 'username banned: '||new.name;
        end if;
    end $$;
create constraint trigger check_banned_username
    after insert on passwd
    for each row
    execute procedure check_banned_username();
```

Tested using:

```
owner@/tmp:postgres> INSERT INTO banned_usernames (name) VALUES ('test');
INSERT 0 1
Time: 0.008s
owner@/tmp:postgres> INSERT INTO hosts (name, maxusers) VALUES ('ny1.hashbang.sh', 5);
INSERT 0 1
Time: 0.008s
owner@/tmp:postgres> INSERT INTO passwd (uid, name, host) VALUES (1001, 'test', 'ny1.hashbang.sh');
username banned: test
CONTEXT:  PL/pgSQL function check_banned_username() line 4 at RAISE

Time: 0.005s
owner@/tmp:postgres>
```

**Comment by RyanSquared** [comment]
this of course means having and maintaining a `banned_usernames` table with: https://ldpreload.com/files/names-to-reserve.txt

**Comment by RyanSquared** [comment]
I realize that my "select 1 from" is probably the wrong way to do it but I'm not sure how to.

**Comment by daurnimator** [comment]
> I realize that my "select 1 from" is probably the wrong way to do it but I'm not sure how to.

`select 1` is fine; but you might want to wrap that in `select exists()`. see e.g. https://stackoverflow.com/a/16467634/282536

**Comment by RyanSquared** [comment]
Should be fixed now.

**Comment by RyanSquared** [comment]
So, it's not fine, actually. Can't have a query inside of a `when` statement.

**Comment by RyanSquared** [comment]
Queries aren't allowed in `when` statements so I moved the logic to the function itself.

My comment has been updated with the new working SQL code, as well as provided a - pretty simple - test case.
