### ISSUE TITLE
Tests shouldn't pull code from the network

### ISSUE THREAD

**Issue by KellerFuchs** [hashbang/userdb#4]
Currently, `make test` pulls `plpgunit` from Github.
I suggest we use a submodule instead, to avoid pulling code over the network unexpectedly, and to ensure that we use a consistent version of it.

**Comment by daurnimator** [comment]
I always avoid submodules as much as possible. A dependency for **testing** is not enough to even vaguely sway that for me.

I don't mind pulling it in over the network if it's not installed.
But we should cache that download if possible.

**Comment by KellerFuchs** [comment]
My issue is more about pulling random code form the network, period, so caching doesn't change anything about it.

**Comment by lrvick** [comment]
@KellerFuchs submodules can be a pain for this sort of thing.

What about pulling the tar.gz on the fly and verifying shasum?

**Comment by lrvick** [comment]
Updated for now so clone only happens if test/plpgunit folder does not exist.

**Comment by KellerFuchs** [comment]
@lrvick I'm not sure what is the difference, UX-wise, between having in the Makefile `git submodule update` and `wget foobar && sha256sum -c foobar.sha256 && tar -xf foobar && rm foobar`, except that one is more annoying to write than the other.

**Comment by lrvick** [comment]
The submodule does seem like the less painful route here, provided the Makefile deals with it. Means our signed commits extend to that as well.

@daurnimator are you ok with this?
